# a=input("Enter something: ")
# print(type(a))
# b=int(input("Enter integer: "))
# print(type(b))
# c=float(input("Enter float: "))
# print(type(c))
print(type(True))
print(type(2))
print(type(12.24))
print(type("hello"))
